/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    posts: Post;
    pages: Page;
    tasks: Task;
    contact: Contact;
    sponsors: Sponsor;
    'magazine-slides': MagazineSlide;
    history: History;
    kommando: Kommando;
    clerk: Clerk;
    'active-members': ActiveMember;
    'fire-brigade-youth': FireBrigadeYouth;
    reserve: Reserve;
    gallery: Gallery;
    impressum: Impressum;
    datenschutz: Datenschutz;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'magazine-slides': MagazineSlidesSelect<false> | MagazineSlidesSelect<true>;
    history: HistorySelect<false> | HistorySelect<true>;
    kommando: KommandoSelect<false> | KommandoSelect<true>;
    clerk: ClerkSelect<false> | ClerkSelect<true>;
    'active-members': ActiveMembersSelect<false> | ActiveMembersSelect<true>;
    'fire-brigade-youth': FireBrigadeYouthSelect<false> | FireBrigadeYouthSelect<true>;
    reserve: ReserveSelect<false> | ReserveSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    impressum: ImpressumSelect<false> | ImpressumSelect<true>;
    datenschutz: DatenschutzSelect<false> | DatenschutzSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    'contact-info': ContactInfo;
    'cookie-banner': CookieBanner;
    'alert-top-bar': AlertTopBar;
    'sidebar-widgets': SidebarWidget;
    'map-settings': MapSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'cookie-banner': CookieBannerSelect<false> | CookieBannerSelect<true>;
    'alert-top-bar': AlertTopBarSelect<false> | AlertTopBarSelect<true>;
    'sidebar-widgets': SidebarWidgetsSelect<false> | SidebarWidgetsSelect<true>;
    'map-settings': MapSettingsSelect<false> | MapSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'de';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'site-admin')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage post categories
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * The display name of the category
   */
  name: string;
  /**
   * URL-friendly version of the name (auto-generated)
   */
  slug: string;
  /**
   * Optional description of the category
   */
  description?: string | null;
  /**
   * Whether this category is active and can be used
   */
  active?: boolean | null;
  /**
   * Optional icon identifier (e.g., emoji or icon name)
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage news articles, operations, training reports, and events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The title of the post
   */
  title: string;
  /**
   * URL-friendly version of the title (auto-generated)
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Select the category for this post
   */
  category: number | Category;
  /**
   * Main image displayed with the post
   */
  featuredImage?: (number | null) | Media;
  /**
   * Multiple images displayed in a slider/gallery on the post page
   */
  galleryImages?: (number | Media)[] | null;
  /**
   * Date when the post was or will be published
   */
  publishedDate?: string | null;
  /**
   * The author of this post (automatically set to logged-in user if not provided)
   */
  author?: (number | null) | User;
  /**
   * If checked, the author will be displayed on the frontend blog post page
   */
  showAuthor?: boolean | null;
  meta?: {
    /**
     * SEO title (defaults to post title if empty)
     */
    metaTitle?: string | null;
    /**
     * SEO description for search engines
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage content pages and navigation menu items. Top items are menu labels only, sub items are full content pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * If checked, this is a top-level menu label (no content/slug needed). If unchecked, this is a submenu item with full content.
   */
  isTopItem?: boolean | null;
  /**
   * Label to display in the navigation menu. For top items, this is required. For sub items, defaults to title if empty.
   */
  menuLabel?: string | null;
  /**
   * Parent top item for submenu items. Required for submenu items. Only top items (isTopItem: true) can be selected as parents.
   */
  menuParent?: (number | null) | Page;
  /**
   * The title of the page. For top items, optional (if provided, slug and content become required). For sub items, required.
   */
  title?: string | null;
  /**
   * Page description or summary (required for submenu items)
   */
  description?: string | null;
  /**
   * URL-friendly version of the title (auto-generated from title if left empty). You can edit this manually.
   */
  slug: string;
  /**
   * The main content of the page. For top items, optional (if title provided, becomes required). For sub items, required.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * SEO title (defaults to page title if empty). Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * SEO description for search engines. Recommended length: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional)
     */
    metaKeywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage tasks displayed on the home page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  /**
   * Task title (e.g., "Rescue", "Extinguish")
   */
  title: string;
  /**
   * Task description
   */
  description: string;
  /**
   * Upload a custom SVG or image icon for this task. If provided, this will be used instead of the default icon.
   */
  iconImage?: (number | null) | Media;
  /**
   * Select a default icon for this task (used if no custom icon image is uploaded)
   */
  icon?: ('rescue' | 'extinguish' | 'recover' | 'protect') | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage contact form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * Full name of the person submitting the form
   */
  name: string;
  /**
   * Email address for contact
   */
  email: string;
  /**
   * Phone number (optional)
   */
  phone?: string | null;
  /**
   * Subject of the message
   */
  subject: string;
  /**
   * Message content
   */
  message: string;
  /**
   * Status of the contact submission
   */
  status?: ('new' | 'in_progress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage sponsors displayed on the home page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  /**
   * Sponsor name
   */
  name: string;
  /**
   * Sponsor logo image
   */
  logo: number | Media;
  /**
   * Sponsor website URL (optional)
   */
  website?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage slides for the home page magazine slider
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-slides".
 */
export interface MagazineSlide {
  id: number;
  title: string;
  /**
   * Author email (automatically filled from logged-in user if not provided)
   */
  author?: string | null;
  /**
   * If checked, the author will be displayed on the magazine slider
   */
  showAuthor?: boolean | null;
  /**
   * Short description or excerpt
   */
  excerpt?: string | null;
  /**
   * Slide background image
   */
  image: number | Media;
  /**
   * Related article/post to link to
   */
  post: number | Post;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Publication date
   */
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage history timeline events and content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history".
 */
export interface History {
  id: number;
  /**
   * Image displayed on the left side of the hero banner
   */
  heroImage?: (number | null) | Media;
  /**
   * Large title displayed in the hero section
   */
  heroTitle?: string | null;
  /**
   * Subtitle displayed below the hero title
   */
  heroSubtitle?: string | null;
  /**
   * First paragraph in the hero section
   */
  heroParagraph1?: string | null;
  /**
   * Second paragraph in the hero section
   */
  heroParagraph2?: string | null;
  /**
   * Third paragraph in the hero section
   */
  heroParagraph3?: string | null;
  timelineEvents?:
    | {
        /**
         * Year of the event (e.g., "1883")
         */
        year: string;
        /**
         * Header text displayed at the top of the timeline card
         */
        header?: string | null;
        /**
         * Description of the historical event
         */
        description: string;
        /**
         * Optional image for this timeline event
         */
        image?: (number | null) | Media;
        /**
         * Optional video URL (YouTube, Vimeo, etc.)
         */
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    /**
     * SEO title (defaults to page title if empty)
     */
    metaTitle?: string | null;
    /**
     * SEO description for search engines
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage the kommando page heading and team members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kommando".
 */
export interface Kommando {
  id: number;
  /**
   * Main title displayed in the hero section
   */
  title: string;
  /**
   * Introduction paragraph displayed below the title
   */
  intro: string;
  teamMembers?:
    | {
        /**
         * Full name of the team member
         */
        name: string;
        /**
         * Position/role (e.g., "Commander", "Deputy Commander")
         */
        position: string;
        /**
         * Rank abbreviation (e.g., "HBI", "BI", "V")
         */
        rank: string;
        /**
         * Contact email address
         */
        email: string;
        /**
         * Profile image of the team member (displayed as full image on card)
         */
        image: number | Media;
        /**
         * Short biography text about the team member
         */
        bio?: string | null;
        /**
         * Optional audio file for the team member bio
         */
        audio?: (number | null) | Media;
        cardMedia?: {
          /**
           * Select whether to show an image or video on the card
           */
          mediaType?: ('none' | 'image' | 'video') | null;
          image?: (number | null) | Media;
          /**
           * Video URL (YouTube, Vimeo, etc.)
           */
          videoUrl?: string | null;
        };
        /**
         * Display order (lower numbers appear first)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the clerk page heading and team members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clerk".
 */
export interface Clerk {
  id: number;
  /**
   * Main title displayed in the hero section
   */
  title: string;
  /**
   * Introduction paragraph displayed below the title
   */
  intro: string;
  teamMembers?:
    | {
        /**
         * Full name of the team member
         */
        name: string;
        /**
         * Position/role (e.g., "Clerk", "Deputy Clerk")
         */
        position: string;
        /**
         * Rank abbreviation (e.g., "HBI", "BI", "V")
         */
        rank: string;
        /**
         * Contact email address
         */
        email: string;
        /**
         * Profile image of the team member (displayed as full image on card)
         */
        image: number | Media;
        /**
         * Short biography text about the team member
         */
        bio?: string | null;
        /**
         * Optional audio file for the team member bio
         */
        audio?: (number | null) | Media;
        cardMedia?: {
          /**
           * Select whether to show an image or video on the card
           */
          mediaType?: ('none' | 'image' | 'video') | null;
          image?: (number | null) | Media;
          /**
           * Video URL (YouTube, Vimeo, etc.)
           */
          videoUrl?: string | null;
        };
        /**
         * Display order (lower numbers appear first)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the active members page heading and team members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-members".
 */
export interface ActiveMember {
  id: number;
  /**
   * Main title displayed in the hero section
   */
  title: string;
  /**
   * Introduction paragraph displayed below the title
   */
  intro: string;
  teamMembers?:
    | {
        /**
         * Full name of the team member
         */
        name: string;
        /**
         * Position/role (e.g., "Active Member", "Volunteer")
         */
        position: string;
        /**
         * Rank abbreviation (e.g., "HBI", "BI", "V")
         */
        rank: string;
        /**
         * Contact email address
         */
        email: string;
        /**
         * Profile image of the team member (displayed as full image on card)
         */
        image: number | Media;
        /**
         * Short biography text about the team member
         */
        bio?: string | null;
        /**
         * Optional audio file for the team member bio
         */
        audio?: (number | null) | Media;
        cardMedia?: {
          /**
           * Select whether to show an image or video on the card
           */
          mediaType?: ('none' | 'image' | 'video') | null;
          image?: (number | null) | Media;
          /**
           * Video URL (YouTube, Vimeo, etc.)
           */
          videoUrl?: string | null;
        };
        /**
         * Display order (lower numbers appear first)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the fire brigade youth page heading and team members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fire-brigade-youth".
 */
export interface FireBrigadeYouth {
  id: number;
  /**
   * Main title displayed in the hero section
   */
  title: string;
  /**
   * Introduction paragraph displayed below the title
   */
  intro: string;
  teamMembers?:
    | {
        /**
         * Full name of the team member
         */
        name: string;
        /**
         * Position/role (e.g., "Youth Leader", "Youth Member")
         */
        position: string;
        /**
         * Rank abbreviation (e.g., "HBI", "BI", "V")
         */
        rank: string;
        /**
         * Contact email address
         */
        email: string;
        /**
         * Profile image of the team member (displayed as full image on card)
         */
        image: number | Media;
        /**
         * Short biography text about the team member
         */
        bio?: string | null;
        /**
         * Optional audio file for the team member bio
         */
        audio?: (number | null) | Media;
        cardMedia?: {
          /**
           * Select whether to show an image or video on the card
           */
          mediaType?: ('none' | 'image' | 'video') | null;
          image?: (number | null) | Media;
          /**
           * Video URL (YouTube, Vimeo, etc.)
           */
          videoUrl?: string | null;
        };
        /**
         * Display order (lower numbers appear first)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the reserve page heading and team members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reserve".
 */
export interface Reserve {
  id: number;
  /**
   * Main title displayed in the hero section
   */
  title: string;
  /**
   * Introduction paragraph displayed below the title
   */
  intro: string;
  teamMembers?:
    | {
        /**
         * Full name of the team member
         */
        name: string;
        /**
         * Position/role (e.g., "Reserve Member", "Reserve Leader")
         */
        position: string;
        /**
         * Rank abbreviation (e.g., "HBI", "BI", "V")
         */
        rank: string;
        /**
         * Contact email address
         */
        email: string;
        /**
         * Profile image of the team member (displayed as full image on card)
         */
        image: number | Media;
        /**
         * Short biography text about the team member
         */
        bio?: string | null;
        /**
         * Optional audio file for the team member bio
         */
        audio?: (number | null) | Media;
        cardMedia?: {
          /**
           * Select whether to show an image or video on the card
           */
          mediaType?: ('none' | 'image' | 'video') | null;
          image?: (number | null) | Media;
          /**
           * Video URL (YouTube, Vimeo, etc.)
           */
          videoUrl?: string | null;
        };
        /**
         * Display order (lower numbers appear first)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Select the type of media (image, video, or audio)
   */
  mediaType: 'image' | 'video' | 'audio';
  /**
   * Upload an image, video, or audio file
   */
  media: number | Media;
  /**
   * Order in which items appear in the gallery (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Mark this item as featured (will appear more prominently)
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage Impressum (Legal Notice) page content. Only one record can exist.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum".
 */
export interface Impressum {
  id: number;
  title: string;
  /**
   * Short description or subtitle displayed below the title
   */
  description?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    /**
     * SEO title (defaults to page title if empty)
     */
    metaTitle?: string | null;
    /**
     * SEO description for search engines
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage Datenschutz (Privacy Policy) page content. Only one record can exist.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz".
 */
export interface Datenschutz {
  id: number;
  title: string;
  /**
   * Short description or subtitle displayed below the title
   */
  description?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    /**
     * SEO title (defaults to page title if empty)
     */
    metaTitle?: string | null;
    /**
     * SEO description for search engines
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'contact';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'magazine-slides';
        value: number | MagazineSlide;
      } | null)
    | ({
        relationTo: 'history';
        value: number | History;
      } | null)
    | ({
        relationTo: 'kommando';
        value: number | Kommando;
      } | null)
    | ({
        relationTo: 'clerk';
        value: number | Clerk;
      } | null)
    | ({
        relationTo: 'active-members';
        value: number | ActiveMember;
      } | null)
    | ({
        relationTo: 'fire-brigade-youth';
        value: number | FireBrigadeYouth;
      } | null)
    | ({
        relationTo: 'reserve';
        value: number | Reserve;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'impressum';
        value: number | Impressum;
      } | null)
    | ({
        relationTo: 'datenschutz';
        value: number | Datenschutz;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  active?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  category?: T;
  featuredImage?: T;
  galleryImages?: T;
  publishedDate?: T;
  author?: T;
  showAuthor?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  isTopItem?: T;
  menuLabel?: T;
  menuParent?: T;
  title?: T;
  description?: T;
  slug?: T;
  content?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  iconImage?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-slides_select".
 */
export interface MagazineSlidesSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  showAuthor?: T;
  excerpt?: T;
  image?: T;
  post?: T;
  order?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history_select".
 */
export interface HistorySelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroParagraph1?: T;
  heroParagraph2?: T;
  heroParagraph3?: T;
  timelineEvents?:
    | T
    | {
        year?: T;
        header?: T;
        description?: T;
        image?: T;
        videoUrl?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kommando_select".
 */
export interface KommandoSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        position?: T;
        rank?: T;
        email?: T;
        image?: T;
        bio?: T;
        audio?: T;
        cardMedia?:
          | T
          | {
              mediaType?: T;
              image?: T;
              videoUrl?: T;
            };
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clerk_select".
 */
export interface ClerkSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        position?: T;
        rank?: T;
        email?: T;
        image?: T;
        bio?: T;
        audio?: T;
        cardMedia?:
          | T
          | {
              mediaType?: T;
              image?: T;
              videoUrl?: T;
            };
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-members_select".
 */
export interface ActiveMembersSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        position?: T;
        rank?: T;
        email?: T;
        image?: T;
        bio?: T;
        audio?: T;
        cardMedia?:
          | T
          | {
              mediaType?: T;
              image?: T;
              videoUrl?: T;
            };
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fire-brigade-youth_select".
 */
export interface FireBrigadeYouthSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        position?: T;
        rank?: T;
        email?: T;
        image?: T;
        bio?: T;
        audio?: T;
        cardMedia?:
          | T
          | {
              mediaType?: T;
              image?: T;
              videoUrl?: T;
            };
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reserve_select".
 */
export interface ReserveSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        position?: T;
        rank?: T;
        email?: T;
        image?: T;
        bio?: T;
        audio?: T;
        cardMedia?:
          | T
          | {
              mediaType?: T;
              image?: T;
              videoUrl?: T;
            };
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  mediaType?: T;
  media?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum_select".
 */
export interface ImpressumSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz_select".
 */
export interface DatenschutzSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage address information displayed on the contact page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  /**
   * Fire Department address and contact details. Use rich text formatting for better presentation.
   */
  address?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage cookie banner settings and content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner".
 */
export interface CookieBanner {
  id: number;
  /**
   * Show or hide the cookie banner on the website
   */
  enabled?: boolean | null;
  /**
   * Increase this when you change cookie purposes to re-request consent.
   */
  version?: number | null;
  /**
   * The title displayed in the cookie banner
   */
  title?: string | null;
  /**
   * The description text displayed in the cookie banner
   */
  description?: string | null;
  /**
   * The text displayed on the main action button (e.g. “Accept all”).
   */
  buttonText?: string | null;
  /**
   * Text for the button that rejects non-essential cookies.
   */
  rejectButtonText?: string | null;
  /**
   * Text for the button that saves the selected categories.
   */
  saveButtonText?: string | null;
  essentialLabel?: string | null;
  essentialDescription?: string | null;
  showAnalytics?: boolean | null;
  analyticsLabel?: string | null;
  analyticsDescription?: string | null;
  showMarketing?: boolean | null;
  marketingLabel?: string | null;
  marketingDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the live alert bar shown at the top of the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert-top-bar".
 */
export interface AlertTopBar {
  id: number;
  /**
   * Show or hide the alert bar
   */
  active?: boolean | null;
  title?: string | null;
  description?: string | null;
  color?: ('red' | 'yellow' | 'orange' | 'purple' | 'green') | null;
  /**
   * Select a post to link to from the alert bar
   */
  post?: (number | null) | Post;
  /**
   * Optional custom label for the read more button
   */
  readMoreText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage social media widgets displayed in the news sidebar
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebar-widgets".
 */
export interface SidebarWidget {
  id: number;
  facebook?: {
    enabled?: boolean | null;
    /**
     * Full URL to your Facebook page (e.g., https://web.facebook.com/ffdross)
     */
    pageUrl?: string | null;
  };
  instagram?: {
    enabled?: boolean | null;
    /**
     * Instagram username without @ (e.g., ff_dross)
     */
    username?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure Google Maps or OpenStreetMap display on the contact page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-settings".
 */
export interface MapSetting {
  id: number;
  /**
   * Enable or disable the map display on the contact page
   */
  enabled?: boolean | null;
  /**
   * Choose between Google Maps or OpenStreetMap
   */
  mapType: 'google' | 'osm';
  /**
   * Add multiple addresses/locations to display on the map
   */
  mapLocations?:
    | {
        /**
         * Title for this location (e.g., "Main Station", "Branch Office")
         */
        title: string;
        /**
         * Full address for this location
         */
        address: string;
        /**
         * Paste the iframe src URL from Google Maps. To get this: 1) Go to https://www.google.com/maps, 2) Search for the address, 3) Click "Share" → "Embed a map", 4) Copy the src URL
         */
        googleMapsEmbedUrl?: string | null;
        /**
         * Latitude coordinate (e.g., 48.123456)
         */
        latitude?: number | null;
        /**
         * Longitude coordinate (e.g., 15.123456)
         */
        longitude?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How to display multiple locations: show all on one map, show only the first, or allow users to switch between them
   */
  displayMode?: ('all' | 'first' | 'switchable') | null;
  /**
   * Title displayed above the map
   */
  mapTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage basic site-wide configuration including site name, description, logo, and favicon
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The site name/title displayed in browser tabs and metadata
   */
  siteName: string;
  /**
   * Meta description for SEO and social sharing
   */
  siteDescription?: string | null;
  /**
   * Main site logo image
   */
  logo?: (number | null) | Media;
  /**
   * Site favicon displayed in browser tabs
   */
  favicon?: (number | null) | Media;
  /**
   * Custom logo displayed in the Payload admin panel. If not set, the default Payload logo will be used.
   */
  adminLogo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner_select".
 */
export interface CookieBannerSelect<T extends boolean = true> {
  enabled?: T;
  version?: T;
  title?: T;
  description?: T;
  buttonText?: T;
  rejectButtonText?: T;
  saveButtonText?: T;
  essentialLabel?: T;
  essentialDescription?: T;
  showAnalytics?: T;
  analyticsLabel?: T;
  analyticsDescription?: T;
  showMarketing?: T;
  marketingLabel?: T;
  marketingDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert-top-bar_select".
 */
export interface AlertTopBarSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  description?: T;
  color?: T;
  post?: T;
  readMoreText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebar-widgets_select".
 */
export interface SidebarWidgetsSelect<T extends boolean = true> {
  facebook?:
    | T
    | {
        enabled?: T;
        pageUrl?: T;
      };
  instagram?:
    | T
    | {
        enabled?: T;
        username?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-settings_select".
 */
export interface MapSettingsSelect<T extends boolean = true> {
  enabled?: T;
  mapType?: T;
  mapLocations?:
    | T
    | {
        title?: T;
        address?: T;
        googleMapsEmbedUrl?: T;
        latitude?: T;
        longitude?: T;
        id?: T;
      };
  displayMode?: T;
  mapTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  adminLogo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}